extends:
  - airbnb-base
  - 'plugin:prettier/recommended'
root: true
env:
  browser: true
  es6: true
  node: true
globals:
  Drupal: true
  drupalSettings: true
  drupalTranslations: true
  jQuery: true
  domready: true
  debounce: true
  once: true
  Dropdown: true
  Collapse: true
  Filters: true
  Menu: true
  Top: true
parser: '@babel/eslint-parser'
parserOptions:
  babelOptions:
    configFile: './build/babel.config.json'
rules:
  prettier/prettier: error
  class-methods-use-this: 'off'
  consistent-return:
    - 'off'
  no-underscore-dangle:
    - 'off'
  max-nested-callbacks:
    - warn
    - 3
  import/no-mutable-exports:
    - warn
  no-plusplus:
    - warn
    - allowForLoopAfterthoughts: true
  no-param-reassign:
    - 'off'
  no-prototype-builtins:
    - 'off'
  valid-jsdoc:
    - warn
    - prefer:
        returns: return
        property: prop
      requireReturn: false
  no-unused-vars:
    - warn
  operator-linebreak:
    - error
    - after
    - overrides:
        '?': ignore
        ':': ignore
